package com.example.ui.theme

object Translations {
    private val en = mapOf(
        "app_name" to "OmniAgency",
        "dashboard" to "Dashboard",
        "clients" to "Clients",
        "employees" to "Employees",
        "projects" to "Projects",
        "tasks" to "Tasks",
        "calendar" to "Calendar",
        "payments" to "Payments",
        "notifications" to "Notifications",
        "reports" to "Reports",
        "activity" to "Activity Log",
        "settings" to "Settings",
        "search" to "Search",
        "total_clients" to "Total Clients",
        "active_clients" to "Active Clients",
        "total_projects" to "Total Projects",
        "active_projects" to "Active Projects",
        "completed_projects" to "Completed Projects",
        "delayed_projects" to "Delayed Projects",
        "open_tasks" to "Open Tasks",
        "completed_tasks" to "Completed Tasks",
        "total_revenue" to "Total Revenue",
        "pending_payments" to "Pending Payments",
        "needs_attention" to "Needs Attention",
        "quick_actions" to "Quick Actions",
        "new_client" to "New Client",
        "new_project" to "New Project",
        "new_task" to "New Task",
        "new_payment" to "New Payment",
        "new_reminder" to "New Reminder",
        "role_admin" to "Admin",
        "role_manager" to "Manager",
        "role_employee" to "Employee",
        "switch_role" to "Role Preview",
        "health_good" to "Healthy",
        "health_attention" to "Attention",
        "health_at_risk" to "At Risk",
        "status" to "Status",
        "priority" to "Priority",
        "deadline" to "Deadline",
        "save" to "Save",
        "cancel" to "Cancel",
        "delete" to "Delete",
        "edit" to "Edit",
        "add" to "Add",
        "done" to "Done",
        "in_progress" to "In Progress",
        "review" to "Review",
        "todo" to "To Do",
        "deliver" to "Deliver Project",
        "delivered" to "Delivered",
        "export_csv" to "Export CSV"
    )

    private val fr = mapOf(
        "app_name" to "OmniAgency",
        "dashboard" to "Tableau de Bord",
        "clients" to "Clients",
        "employees" to "Équipe",
        "projects" to "Projets",
        "tasks" to "Tâches",
        "calendar" to "Calendrier",
        "payments" to "Paiements",
        "notifications" to "Notifications",
        "reports" to "Rapports",
        "activity" to "Activités",
        "settings" to "Paramètres",
        "search" to "Recherche",
        "total_clients" to "Total Clients",
        "active_clients" to "Clients Actifs",
        "total_projects" to "Total Projets",
        "active_projects" to "Projets Actifs",
        "completed_projects" to "Projets Terminés",
        "delayed_projects" to "Projets Retardés",
        "open_tasks" to "Tâches Ouvertes",
        "completed_tasks" to "Tâches Terminées",
        "total_revenue" to "Chiffre d'Affaires",
        "pending_payments" to "Paiements en Attente",
        "needs_attention" to "Nécessite Attention",
        "quick_actions" to "Actions Rapides",
        "new_client" to "Nouveau Client",
        "new_project" to "Nouveau Projet",
        "new_task" to "Nouvelle Tâche",
        "new_payment" to "Nouveau Paiement",
        "new_reminder" to "Nouveau Rappel",
        "role_admin" to "Admin",
        "role_manager" to "Manager",
        "role_employee" to "Employé",
        "switch_role" to "Aperçu de Rôle",
        "health_good" to "Sain",
        "health_attention" to "Attention",
        "health_at_risk" to "À Risque",
        "status" to "Statut",
        "priority" to "Priorité",
        "deadline" to "Échéance",
        "save" to "Enregistrer",
        "cancel" to "Annuler",
        "delete" to "Supprimer",
        "edit" to "Modifier",
        "add" to "Ajouter",
        "done" to "Terminé",
        "in_progress" to "En Cours",
        "review" to "En Révision",
        "todo" to "À Faire",
        "deliver" to "Livrer le Projet",
        "delivered" to "Livré",
        "export_csv" to "Exporter CSV"
    )

    private val ar = mapOf(
        "app_name" to "OmniAgency",
        "dashboard" to "لوحة التحكم",
        "clients" to "العملاء",
        "employees" to "فريق العمل",
        "projects" to "المشاريع",
        "tasks" to "المهام",
        "calendar" to "التقويم",
        "payments" to "المدفوعات",
        "notifications" to "الإشعارات",
        "reports" to "التقارير",
        "activity" to "سجل النشاط",
        "settings" to "الإعدادات",
        "search" to "بحث",
        "total_clients" to "إجمالي العملاء",
        "active_clients" to "العملاء النشطون",
        "total_projects" to "إجمالي المشاريع",
        "active_projects" to "المشاريع النشطة",
        "completed_projects" to "المشاريع المكتملة",
        "delayed_projects" to "المشاريع المتأخرة",
        "open_tasks" to "المهام المفتوحة",
        "completed_tasks" to "المهام المنجزة",
        "total_revenue" to "إجمالي الإيرادات",
        "pending_payments" to "المدفوعات المعلقة",
        "needs_attention" to "يحتاج إلى انتباه",
        "quick_actions" to "إجراءات سريعة",
        "new_client" to "عميل جديد",
        "new_project" to "مشروع جديد",
        "new_task" to "مهمة جديدة",
        "new_payment" to "دفعة جديدة",
        "new_reminder" to "تذكير جديد",
        "role_admin" to "مدير النظام",
        "role_manager" to "مشرف",
        "role_employee" to "موظف",
        "switch_role" to "معاينة الدور",
        "health_good" to "ممتاز",
        "health_attention" to "انتباه",
        "health_at_risk" to "في خطر",
        "status" to "الحالة",
        "priority" to "الأولوية",
        "deadline" to "الموعد النهائي",
        "save" to "حفظ",
        "cancel" to "إلغاء",
        "delete" to "حذف",
        "edit" to "تعديل",
        "add" to "إضافة",
        "done" to "مكتمل",
        "in_progress" to "قيد التنفيذ",
        "review" to "مراجعة",
        "todo" to "قيد الانتظار",
        "deliver" to "تسليم المشروع",
        "delivered" to "تم التسليم",
        "export_csv" to "تصدير CSV"
    )

    fun get(key: String, language: String): String {
        val dict = when (language) {
            "fr" -> fr
            "ar" -> ar
            else -> en
        }
        return dict[key] ?: en[key] ?: key
    }
}
